auto_num_workers: false
data_format: coco_instances
data_root: /home/kprokofi/detection_bench_datasets/detection/wgisd_merged_coco_small
device: gpu
ignore_index: 255
task: INSTANCE_SEGMENTATION
test_subset: !!python/object:otx.config.data.SubsetConfig
  batch_size: 1
  input_size: null
  num_workers: 4
  sampler: !!python/object:otx.config.data.SamplerConfig
    class_path: torch.utils.data.RandomSampler
    init_args: {}
  subset_name: test
  to_tv_image: true
  transform_lib_type: !!python/object/apply:otx.types.transformer_libs.TransformLibType
  - TORCHVISION
  transforms:
  - class_path: otx.data.transform_libs.torchvision.Resize
    init_args:
      is_numpy_to_tvtensor: false
      keep_ratio: true
      scale: $(input_size)
  - class_path: otx.data.transform_libs.torchvision.Pad
    init_args:
      pad_to_square: true
      size_divisor: 32
  - class_path: torchvision.transforms.v2.ToDtype
    init_args:
      dtype: &id001 ${as_torch_dtype:torch.float32}
  - class_path: torchvision.transforms.v2.Normalize
    init_args:
      mean:
      - 123.675
      - 116.28
      - 103.53
      std:
      - 1.0
      - 1.0
      - 1.0
tile_config: !!python/object:otx.config.data.TileConfig
  enable_adaptive_tiling: true
  enable_tiler: false
  iou_threshold: 0.45
  max_num_instances: 1500
  object_tile_ratio: 0.03
  overlap: 0.2
  sampling_ratio: 1.0
  tile_size: !!python/tuple
  - 400
  - 400
train_subset: !!python/object:otx.config.data.SubsetConfig
  batch_size: 4
  input_size: null
  num_workers: 8
  sampler: !!python/object:otx.config.data.SamplerConfig
    class_path: otx.data.samplers.balanced_sampler.BalancedSampler
    init_args: {}
  subset_name: train
  to_tv_image: true
  transform_lib_type: !!python/object/apply:otx.types.transformer_libs.TransformLibType
  - TORCHVISION
  transforms:
  - class_path: otx.data.transform_libs.torchvision.Resize
    init_args:
      keep_ratio: true
      scale: $(input_size)
      transform_bbox: true
      transform_mask: true
  - class_path: torchvision.transforms.v2.RandomPhotometricDistort
    enable: false
    init_args:
      brightness:
      - 0.875
      - 1.125
      contrast:
      - 0.5
      - 1.5
      hue:
      - -0.05
      - 0.05
      p: 0.5
      saturation:
      - 0.5
      - 1.5
  - class_path: otx.data.transform_libs.torchvision.RandomAffine
    enable: false
    init_args:
      is_numpy_to_tvtensor: false
      max_rotate_degree: 10.0
      max_shear_degree: 2.0
      max_translate_ratio: 0.1
      scaling_ratio_range:
      - 0.5
      - 1.5
  - class_path: otx.data.transform_libs.torchvision.Pad
    enable: true
    init_args:
      pad_to_square: true
      size_divisor: 32
      transform_mask: true
  - class_path: otx.data.transform_libs.torchvision.RandomFlip
    enable: true
    init_args:
      probability: 0.5
  - class_path: torchvision.transforms.v2.RandomVerticalFlip
    enable: false
    init_args:
      p: 0.5
  - class_path: otx.data.transform_libs.torchvision.RandomGaussianBlur
    enable: false
    init_args:
      kernel_size: 5
      probability: 0.5
      sigma:
      - 0.1
      - 2.0
  - class_path: torchvision.transforms.v2.ToDtype
    init_args:
      dtype: *id001
  - class_path: otx.data.transform_libs.torchvision.RandomGaussianNoise
    enable: false
    init_args:
      mean: 0.0
      probability: 0.5
      sigma: 0.1
  - class_path: torchvision.transforms.v2.Normalize
    init_args:
      mean:
      - 123.675
      - 116.28
      - 103.53
      std:
      - 1.0
      - 1.0
      - 1.0
unannotated_items_ratio: 0.0
val_subset: !!python/object:otx.config.data.SubsetConfig
  batch_size: 1
  input_size: null
  num_workers: 4
  sampler: !!python/object:otx.config.data.SamplerConfig
    class_path: torch.utils.data.RandomSampler
    init_args: {}
  subset_name: val
  to_tv_image: true
  transform_lib_type: !!python/object/apply:otx.types.transformer_libs.TransformLibType
  - TORCHVISION
  transforms:
  - class_path: otx.data.transform_libs.torchvision.Resize
    init_args:
      is_numpy_to_tvtensor: false
      keep_ratio: true
      scale: $(input_size)
  - class_path: otx.data.transform_libs.torchvision.Pad
    init_args:
      pad_to_square: true
      size_divisor: 32
  - class_path: torchvision.transforms.v2.ToDtype
    init_args:
      dtype: *id001
  - class_path: torchvision.transforms.v2.Normalize
    init_args:
      mean:
      - 123.675
      - 116.28
      - 103.53
      std:
      - 1.0
      - 1.0
      - 1.0
